INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Black'),	'#000000', 0,0,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('White'),	'#FFFFFF', 255,255,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Red'),	'#FF0000', 255,0,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Lime'),	'#00FF00', 0,255,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Blue'),	'#0000FF', 0,0,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Yellow'),	'#FFFF00', 255,255,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Cyan / Aqua'),	'#00FFFF', 0,255,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Magenta / Fuchsia'),	'#FF00FF', 255,0,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Silver'),	'#C0C0C0', 192,192,192);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Gray'),	'#808080', 128,128,128);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Maroon'),	'#800000', 128,0,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Olive'),	'#808000', 128,128,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Green'),	'#008000', 0,128,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Purple'),	'#800080', 128,0,128);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Teal'),	'#008080', 0,128,128);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('Navy'),	'#000080', 0,0,128);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark red'),	'#8B0000', 139,0,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('brown'),	'#A52A2A', 165,42,42);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('firebrick'),	'#B22222', 178,34,34);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('crimson'),	'#DC143C', 220,20,60);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('tomato'),	'#FF6347', 255,99,71);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('coral'),	'#FF7F50', 255,127,80);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('indian red'),	'#CD5C5C', 205,92,92);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light coral'),	'#F08080', 240,128,128);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark salmon'),	'#E9967A', 233,150,122);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('salmon'),	'#FA8072', 250,128,114);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light salmon'),	'#FFA07A', 255,160,122);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('orange red'),	'#FF4500', 255,69,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark orange'),	'#FF8C00', 255,140,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('orange'),	'#FFA500', 255,165,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('gold'),	'#FFD700', 255,215,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark golden rod'),	'#B8860B', 184,134,11);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('golden rod'),	'#DAA520', 218,165,32);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('pale golden rod'),	'#EEE8AA', 238,232,170);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark khaki'),	'#BDB76B', 189,183,107);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('khaki'),	'#F0E68C', 240,230,140);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('yellow green'),	'#9ACD32', 154,205,50);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark olive green'),	'#556B2F', 85,107,47);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('olive drab'),	'#6B8E23', 107,142,35);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('lawn green'),	'#7CFC00', 124,252,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('chart reuse'),	'#7FFF00', 127,255,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('green yellow'),	'#ADFF2F', 173,255,47);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark green'),	'#006400', 0,100,0);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('forest green'),	'#228B22', 34,139,34);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('lime green'),	'#32CD32', 50,205,50);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light green'),	'#90EE90', 144,238,144);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('pale green'),	'#98FB98', 152,251,152);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark sea green'),	'#8FBC8F', 143,188,143);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium spring green'),	'#00FA9A', 0,250,154);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('spring green'),	'#00FF7F', 0,255,127);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('sea green'),	'#2E8B57', 46,139,87);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium aqua marine'),	'#66CDAA', 102,205,170);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium sea green'),	'#3CB371', 60,179,113);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light sea green'),	'#20B2AA', 32,178,170);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark slate gray'),	'#2F4F4F', 47,79,79);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark cyan'),	'#008B8B', 0,139,139);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light cyan'),	'#E0FFFF', 224,255,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark turquoise'),	'#00CED1', 0,206,209);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('turquoise'),	'#40E0D0', 64,224,208);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium turquoise'),	'#48D1CC', 72,209,204);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('pale turquoise'),	'#AFEEEE', 175,238,238);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('aqua marine'),	'#7FFFD4', 127,255,212);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('powder blue'),	'#B0E0E6', 176,224,230);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('cadet blue'),	'#5F9EA0', 95,158,160);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('steel blue'),	'#4682B4', 70,130,180);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('corn flower blue'),	'#6495ED', 100,149,237);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('deep sky blue'),	'#00BFFF', 0,191,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dodger blue'),	'#1E90FF', 30,144,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light blue'),	'#ADD8E6', 173,216,230);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('sky blue'),	'#87CEEB', 135,206,235);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light sky blue'),	'#87CEFA', 135,206,250);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('midnight blue'),	'#191970', 25,25,112);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark blue'),	'#00008B', 0,0,139);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium blue'),	'#0000CD', 0,0,205);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('royal blue'),	'#4169E1', 65,105,225);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('blue violet'),	'#8A2BE2', 138,43,226);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('indigo'),	'#4B0082', 75,0,130);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark slate blue'),	'#483D8B', 72,61,139);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('slate blue'),	'#6A5ACD', 106,90,205);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium slate blue'),	'#7B68EE', 123,104,238);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium purple'),	'#9370DB', 147,112,219);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark magenta'),	'#8B008B', 139,0,139);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark violet'),	'#9400D3', 148,0,211);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark orchid'),	'#9932CC', 153,50,204);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium orchid'),	'#BA55D3', 186,85,211);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('thistle'),	'#D8BFD8', 216,191,216);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('plum'),	'#DDA0DD', 221,160,221);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('violet'),	'#EE82EE', 238,130,238);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('orchid'),	'#DA70D6', 218,112,214);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('medium violet red'),	'#C71585', 199,21,133);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('pale violet red'),	'#DB7093', 219,112,147);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('deep pink'),	'#FF1493', 255,20,147);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('hot pink'),	'#FF69B4', 255,105,180);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light pink'),	'#FFB6C1', 255,182,193);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('pink'),	'#FFC0CB', 255,192,203);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('antique white'),	'#FAEBD7', 250,235,215);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('beige'),	'#F5F5DC', 245,245,220);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('bisque'),	'#FFE4C4', 255,228,196);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('blanched almond'),	'#FFEBCD', 255,235,205);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('wheat'),	'#F5DEB3', 245,222,179);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('corn silk'),	'#FFF8DC', 255,248,220);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('lemon chiffon'),	'#FFFACD', 255,250,205);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light golden rod yellow'),	'#FAFAD2', 250,250,210);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light yellow'),	'#FFFFE0', 255,255,224);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('saddle brown'),	'#8B4513', 139,69,19);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('sienna'),	'#A0522D', 160,82,45);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('chocolate'),	'#D2691E', 210,105,30);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('peru'),	'#CD853F', 205,133,63);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('sandy brown'),	'#F4A460', 244,164,96);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('burly wood'),	'#DEB887', 222,184,135);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('tan'),	'#D2B48C', 210,180,140);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('rosy brown'),	'#BC8F8F', 188,143,143);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('moccasin'),	'#FFE4B5', 255,228,181);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('navajo white'),	'#FFDEAD', 255,222,173);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('peach puff'),	'#FFDAB9', 255,218,185);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('misty rose'),	'#FFE4E1', 255,228,225);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('lavender blush'),	'#FFF0F5', 255,240,245);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('linen'),	'#FAF0E6', 250,240,230);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('old lace'),	'#FDF5E6', 253,245,230);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('papaya whip'),	'#FFEFD5', 255,239,213);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('sea shell'),	'#FFF5EE', 255,245,238);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('mint cream'),	'#F5FFFA', 245,255,250);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('slate gray'),	'#708090', 112,128,144);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light slate gray'),	'#778899', 119,136,153);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light steel blue'),	'#B0C4DE', 176,196,222);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('lavender'),	'#E6E6FA', 230,230,250);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('floral white'),	'#FFFAF0', 255,250,240);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('alice blue'),	'#F0F8FF', 240,248,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('ghost white'),	'#F8F8FF', 248,248,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('honeydew'),	'#F0FFF0', 240,255,240);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('ivory'),	'#FFFFF0', 255,255,240);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('azure'),	'#F0FFFF', 240,255,255);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('snow'),	'#FFFAFA', 255,250,250);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dim gray / dim grey'),	'#696969', 105,105,105);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('dark gray / dark grey'),	'#A9A9A9', 169,169,169);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('light gray / light grey'),	'#D3D3D3', 211,211,211);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('gainsboro'),	'#DCDCDC', 220,220,220);
INSERT INTO `betta_app`.`bus_color` (`col_ds_color`, `col_cd_exacode`, `col_nr_red`, `col_nr_green`, `col_nr_blue`) VALUES (upper('white smoke'),	'#F5F5F5', 245,245,245);