INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo akarensis', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta akarensis Regan', 1910, 'betta-de-akar', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta antoni Tan & Ng', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta aurigans Tan & Ng', 2004, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta balunga Herre', 1940, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta chini Ng', 1993, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta ibanorum Tan and Ng, 2004', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta obscura Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta pinguis Tan and Kottelat', 1998, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo akarensis'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo albimarginata', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta albimarginata Kottelat and Ng', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo albimarginata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta channoides Kottelat and Ng', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo albimarginata'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo anabatoides', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta anabatoides Bleeker', 1851, 'betta gigante', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo anabatoides'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo bellica', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta bellica Sauvage', 1884, 'betta grácil', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo bellica'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta simorum Tan and Ng', 1996, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo bellica'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo coccina', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta brownorum Witte and Schmidt', 1992, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta burdigala Kottelat and Ng', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta coccina Vierke', 1979, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta livida Ng and Kottelat', 1992, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta miniopinna Tan and Tan', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta persephone Schaller', 1986, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta rutilans Witte and Kottelat in Kottelat', 1991, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta tussyae Schaller', 1985, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta uberis Tan & Ng', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo coccina'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo dimidiata', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta dimidiata Roberts', 1989, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo dimidiata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta krataios Tan & Ng', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo dimidiata'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo edithae', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta edithae Vierke', 1984, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo edithae'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo foerschi', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta foerschi Vierke', 1979, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo foerschi'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta mandor Tan & Ng', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo foerschi'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta rubra Perugia', 1893, 'betta-de-toba', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo foerschi'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta strohi Schaller and Kottelat', 1989, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo foerschi'));
/*************************************************************************************/	
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo picta', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta falx Tan and Kottelat', 1998, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo picta'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta picta (Valenciennes, 1846)', 1846, 'betta pintada', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo picta'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta simplex Kottelat', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo picta'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta taeniata Regan', 1910, 'betta-de-borneu', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo picta'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo pugnax', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta breviobesus Tan and Kottelat', 1998, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta cracens Tan & Ng, 2005', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta enisae Kottelat', 1995, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta fusca Regan', 1910, 'betta fusca', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta lehi Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta pallida Schindler & Schmidt', 2004, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta prima Kottelat', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta pugnax (Cantor, 1849)', 1849, 'betta-de-penang', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta pulchra Tan and Tan', 1996, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta raja Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta schalleri Kottelat and Ng, 1994', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta stigmosa Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo pugnax'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_zcomposite`) values ('Complexo splendens', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta imbellis Ladiges', 1975, 'betta-crescente', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo splendens'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta mahachai Panitvong, Nonn', 2002, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo splendens'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta smaragdina Ladiges', 1972, 'betta-verde-esmeralda', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo splendens'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta splendens Regan', 1910, 'peixe-lutador-siamês', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo splendens'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta stiktos Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo splendens'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo unimaculata', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta compuncta Tan & Ng', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta gladiator Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta ideii Tan & Ng', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta macrostoma Regan', 1910, 'betta-ocelada', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta ocellata de Beaufort', 1933, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta pallifina Tan & Ng', 2005, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta patoti Weber and de Beaufort', 1922, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`,   `cfs_nr_year`,   `cfs_ds_descriptcomposite`,  `cfs_st_composite`, `cfs_id_composite`) values ('Betta unimaculata (Popta, 1905)', 1905, 'betta-de-howong', 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo unimaculata'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Complexo waseri', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta chloropharynx Kottelat and Ng', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta hipposideros Ng and Kottelat', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta pi Tan', 1998, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta renata Tan', 1998, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta spilotogena Ng and Kottelat', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta tomi Ng and Kottelat', 1994, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta waseri Krummenacher', 1986, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Complexo waseri'));
/*************************************************************************************/
INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_st_composite`) values ('Sem associação determinada', 'C');
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta apollon Schindler & Schmidt', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Sem associação determinada'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta bangka', 9999, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Sem associação determinada'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta bungbihn', 9999, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Sem associação determinada'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta ferox Schindler & Schmidt', 2006, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Sem associação determinada'));
	INSERT INTO `betta_app`.`bus_compositefish` (`cfs_ds_compositefish`, `cfs_nr_year`, `cfs_st_composite`, `cfs_id_composite`) values ('Betta sukadan', 9999, 'D', (select cfs_id_compositefish from `betta_app`.`bus_compositefish` where `cfs_ds_compositefish` = 'Sem associação determinada'));
	

	
/*
https://pt.wikipedia.org/wiki/Betta

https://pt.wikipedia.org/wiki/Betta_splendens#Variedades
*/
	